services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: mise_en_relation
      POSTGRES_PASSWORD: mise_en_relation
      POSTGRES_DB: mise_en_relation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
